# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # Borders
    border_size = 1

    # Gaps
    gaps_in = 2
    gaps_out = 4

    # Floating Window Gaps
    float_gaps = 4

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {

    # Opacity
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0

    # Use round window corners
    rounding = 10
    rounding_power = 2.0

    # Special Workspaces (scratchpads)
    dim_special = 1
}

# https://wiki.hypr.land/Configuring/Animations/
animations {
    enabled = true
}

# animation = workspaces, 1, 8, default
animation = workspaces, 1, 3, default, slide
animation = specialWorkspaceIn, 1, 3, default, slidefade bottom
animation = specialWorkspaceOut, 1, 3, default, slidefade top
