# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# windowrule = suppressevent maximize, class:.*

# Just no transparency by default
# windowrule = opacity 1 1, match:class .*

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

#####################################
### (omarchy) App-specific tweaks ###

source = ~/.local/share/omarchy/default/hypr/apps.conf

###                               ###
#####################################

#######################################
### Omarchy's floating window rules ###
### (with nmtui added)              ###

windowrule = tag +floating-window, match:class (blueberry.py|Impala|nmtui|Wiremix|org.gnome.NautilusPreviewer|com.gabm.satty|Omarchy|About|TUI.float)

###                                 ###
#######################################

# Override firefox's internal transparency
windowrule = opacity 1.0 override 1.0 override, match:class firefox

# Proton VPN main corner drop-in + settings
$protonclass = proton.vpn.app.gtk
windowrule = move ((monitor_w*1)-416) ((monitor_h*0.02)), match:title (Proton VPN), match:class $protonclass
windowrule = move ((monitor_w*1)-1168) ((monitor_h*0.02)), size 750 (monitor_h*0.96), match:title Settings, match:class protonvpn-app

###########################
### Flatpak windowrules ###

# Speechnote
windowrule = workspace special:SpeechNote, match:class net.mkiol.SpeechNote

# Bitwarden
windowrule = workspace special:Password-Manager, match:class Bitwarden

# Cryptomator
windowrule = workspace special:Cryptomator, match:class org.cryptomator.launcher.Cryptomator$MainApp

###                     ###
###########################
