# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

####################################
##### omarchy's default tweaks #####
###                              ###

source = ~/.local/share/omarchy/default/hypr/apps.conf

# nmtui added to omarchy native window rules
windowrule = tag +floating-window, match:class (blueberry.py|Impala|nmtui|Wiremix|org.gnome.NautilusPreviewer|com.gabm.satty|Omarchy|About|TUI.float)

###                              ###
##### omarchy's default tweaks #####
####################################

####################################
#####   App-Specific Tweaks    #####
###                              ###

# Override firefox's internal transparency
windowrule = opacity 1.0 override 1.0 override, match:class firefox

# Override alacritty's internal transparency
windowrule = opacity 1.0 override 1.0 override, match:class Alacritty

# Override Ghostty's internal transparency
windowrule = opacity 1.0 override 1.0 override, match:class com.mitchellh.ghostty

# Proton VPN main corner drop-in + settings
$protonclass = proton.vpn.app.gtk
windowrule = move ((monitor_w*1)-416) ((monitor_h*0.02)), match:title (Proton VPN), match:class $protonclass
windowrule = move ((monitor_w*1)-1168) ((monitor_h*0.02)), size 750 (monitor_h*0.96), match:title Settings, match:class protonvpn-app

# Gazelle WiFi TUI - floating window
# New Hyprland Syntax using match:initial_class (xdg-terminal-exec and Ghostty friendly)
windowrule = float on, center on, size 800 600, match:initial_class org.omarchy.Gazelle

# Flatpak - Speechnote
windowrule = workspace special:SpeechNote, match:class net.mkiol.SpeechNote

# Flatpak - Bitwarden
windowrule = workspace special:Password-Manager, match:class Bitwarden

# Flatpak - Cryptomator
windowrule = workspace special:Cryptomator, match:class org.cryptomator.launcher.Cryptomator$MainApp

###                              ###
#####   App-Specific Tweaks    #####
####################################

