# Extra autostart processes
# exec-once = uwsm app -- my-service

# center mfact daemon for desired window-
# sizing on master:center orientation
# exec-once = ~/.config/hypr/scripts/center-mfact-daemon.sh

# For some reason, I always have to restart
# xdg-desktop-portal to get screen recording
# or streaming to work...
# exec-once = sleep 5; systemctl --user restart xdg-desktop-portal
