# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # Borders
    border_size = 1

    # Gaps
    gaps_in = 2
    gaps_out = 4

    # Floating Window Gaps
    float_gaps = 4

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {

    # Opacity
    active_opacity = .98
    inactive_opacity = 0.8
    fullscreen_opacity = 1

    # Use round window corners
    rounding = 10
    rounding_power = 2.0

    # Special Workspaces (scratchpads)
    dim_special = 0.4

    # Blur
    blur {
        enabled = true
        new_optimizations = true
        noise = 0.21
        contrast = 1.5
        xray = true
        special = true
        popups = false
        passes = 2

    }
}

# https://wiki.hypr.land/Configuring/Animations/
animations {
    enabled = true
}

# animation = workspaces, 1, 8, default
animation = workspaces, 1, 3, default, slide
animation = specialWorkspaceIn, 1, 3, default, slidefade top
animation = specialWorkspaceOut, 1, 3, default, slidefade bottom

# Disable donation nag
ecosystem {
  no_donation_nag = true
}


source = ~/.config/hypr/windows.conf
